name: CI
on:
  push:
    branches:
      - master
jobs:
  my-testing:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install deps
        run: npm install
      - name: start
        run: npm run lint
