name: CI
on:
  push:
    branches:
      - master
jobs:
  my-testing:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ls dir
        run: ls
        run: pwd
      - name: install deps
        run: npm install
      - name: npm lint
        run: npm run lint
