name: CI
on:
  push:
    branches:
      - master
jobs:
  my-testing:

    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: ls
      - name: git clone
        run: actions/checkout@v4
      - name: checkout
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: ls dir
        run: ls
      - name: pwd    
        run: pwd
      - name: install deps
        run: npm install
      - name: npm lint
        run: npm run lint
