name: CI
on:
  push:
    branches:
      - master
jobs:
  my_testing:

    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: ls -la

      - name: git clone
        uses: actions/checkout@v4

      - name: checkout
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ls dir
        run: ls -la

      - name: pwd    
        run: pwd

      - name: install deps
        run: npm install

      - name: npm dev
        run: npm run dev
